modules:
  - name: 'application'

deps:  
  - "main"

paths:
  libs: "../app/assets/javascripts/libs"
  plugins: "../app/assets/javascripts/plugins"
  vendor: "../app/assets/javascripts/vendor"

  // Libraries
  jquery: "https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"
  lodash: "https://cdnjs.cloudflare.com/ajax/libs/lodash.js/0.8.2/lodash.min.js"
  backbone: "https://cdnjs.cloudflare.com/ajax/libs/backbone.js/0.9.2/backbone-min.js"
  handlebars: "//cdnjs.cloudflare.com/ajax/libs/handlebars.js/1.0.rc.1/handlebars.min.js"

shim:
  backbone: 
    deps: 
      - "lodash"
      - "jquery"
    exports: "Backbone"
  handlebars:
    exports: "Handlebars"

  "plugins/backbone.layoutmanager": 
    deps: 
      - "backbone"


